name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: sepfazeli  # Replace with your GitHub username
          outputs: dist/snake.svg

      # Step 3: Ensure the 'dist' directory exists
      - name: Create dist Directory
        run: mkdir -p dist

      # Step 4: Deploy the snake animation to the `gh-pages` branch
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: gh-pages  # Change this to 'output' if you're using that branch
          build_dir: dist          # Directory where the snake.svg is located
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Use your custom GitHub Personal Access Token
